#!/usr/bin/env python
"""
Intervene: a tool for intersection and visualization of multiple genomic region sets
Created on January 10, 2017
@author: <Aziz Khan>aziz.khan@ncmm.uio.no

"""

import sys
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pybedtools
from pybedtools import BedTool, example_bedtool
from intervene.modules.pairwise import pairwise
from intervene.modules.upset import upset
from intervene.modules.venn import list_venn, genomic_venn
import argparse

from intervene import __version__

def create_dir(dir_path):
    '''
    Create a output directory if it's not exists.
    '''

    if not os.path.exists(dir_path):
        try:
            os.makedirs(dir_path)
        except:
            sys.exit( "Output directory (%s) could not be created." % dir_path )
    return dir_path

def venn_order(input_files):
    """
    Checks the order of venn plot. 

    @type input_files: list[Iterable] 
    @rtype int 

    input
      input_files: a list of files of genomic regions or lists

    return
      len(input_files): return length of input files
    """

    return len(input_files)

def get_filenames(input_files):
    """
    Checks the venn-type

    @type input_files: list[Iterable] 
    @rtype file_names: list[Iterable]

    input
      input_files: a list of files of genomic regions or lists

    return
      file_names:: return a list of file names
    """
    file_names=[]
    for fname in input_files:
      file_names.append(os.path.splitext(os.path.basename(fname))[0].replace(" ", "_"))

    return file_names


"""
Provides access to example files

"""

def data_dir():
    """
    Returns the data directory that contains example files.
    """
    return os.path.join(os.path.dirname(__file__), 'example_data')


def example_filename(fn,sub_dir=None):
    """
    Return a bed file from the pybedtools examples directory.
    This code is adapted from https://github.com/daler/pybedtools

    """
    if sub_dir:
      fn = os.path.join(data_dir(), sub_dir, fn)
    else:
      fn = os.path.join(data_dir(), fn)
    
    if not os.path.exists(fn):
        raise ValueError("%s does not exist" % fn)
    return fn


def get_test_data(module_name):
  '''
  It returns a list of test data files, if the user uses --test argument
  
  @type module_name: chr
  @rtype test_files: list[Iterable]

  input
      module_name: Name of Intervene module

  return
      test_files:: return a list of file paths

  '''

  test_files = []
  
  if module_name == 'venn':
    test_files = [example_filename(i,'ENCODE_hESC') for i in  [
        'H3K27ac.bed',
        'H3K4me2.bed',
        'H3K4me3.bed',
        'H3K27me3.bed'
        ]]

  elif module_name == 'upset':
    test_files = [example_filename(i, 'ENCODE_hESC') for i in  [
        'H3K27ac.bed',
        'H3K4me2.bed',
        'H3K4me1.bed',
        'H3K4me3.bed',
        'H3K27me3.bed'
        ]]

  elif module_name == 'pairwise':
    test_files = [example_filename(i, 'dbSUPER_mm9') for i in  [
        'BoneMarrow.bed',
        'Cerebellum.bed',
        'Cortex.bed',
        'E14.5Brain.bed',
        'E14.5Heart.bed',
        'E14.5Limb.bed',
        'E14.5Liver.bed',
        'Heart.bed',
        'HFSCs.bed',
        'Intestine.bed',
        'Kidney.bed',
        'Liver.bed',
        'Lung.bed',
        'Macrophage.bed',
        'MEF.bed',
        'mESC.bed',
        'Myotubes.bed',
        'Olfactory_Bulb.bed',
        'pro-B.bed',
        'Spleen.bed',
        'TACs.bed',
        'Testis.bed',
        'ThCells.bed',
        'Thymus.bed'
        ]]

  else:

    sys.exit(1)

  return test_files


def main():
    #print 'InterVene: a tool for intersection and visualization of multiple genomic region sets'
    #print 'For more details: https://github.com/asntech/intervene'
    
    desc = """
    
    InterVene: a tool for intersection and visualization of multiple genomic region sets.

    For more details: https://github.com/asntech/intervene

    """
    #print desc
    
    parser = argparse.ArgumentParser(usage='intervene <subcommand> [options]', description=desc)
    subparsers = parser.add_subparsers(dest='command',help='List of subcommands')

    #venn module argument parser
    venn_parser = subparsers.add_parser('venn', usage='intervene venn [options]', 
        description='Create Venn diagram upto 6-way after intersection of genomic regions in <BED/GTF/GFF/VCF> or list sets.', 
        help='Venn diagram of intersection of genomic regions or list sets (upto 6-way).')
    
    venn_parser.add_argument('-i', dest='input', nargs="*",
        help='Input genomic regions in <BED/GTF/GFF/VCF> format or list files. '
        'For files in a directory use *.<extension>. e.g. *.bed')

    venn_parser.add_argument('--type', dest='type', choices=('genomic','list'),
                  help='Type of input sets. Genomic regions or lists of genes sets. ')
   
    venn_parser.add_argument('--names', dest='labels', default='A,B,C,D,E,F',
                  help='Comma-separated list of names for input files. '
                       'Default is: --labels=A,B,C,D,E,F')
    venn_parser.add_argument('--filenames', action='store_true', default=False,
                  help='Use file names as labels instead. '
                       'Default is "%(default)s"')
    venn_parser.add_argument('--colors', dest='colors',
                  help='Comma-separated list of matplotlib-valid colors. '
                       'E.g., --colors=r,b,k')
    
    venn_parser.add_argument('-o', '--output', dest='output', 
                  help='Output folder path where plots will store.'
                       'Default is current working directory.')
    venn_parser.add_argument('--figtype', dest="figtype",choices=('pdf','svg','ps','tiff','png'), 
                   default='pdf',help='Figure type for the plot. '
                       'e.g. --figtype svg. Default is "%(default)s"')    
    venn_parser.add_argument('--figsize', nargs=2, default=(8,10),
                   help='Figure size for the output plot. '
                       'e.g. --figsize=8,10 Default is "%(default)s"')    
    venn_parser.add_argument('--dpi', type=int, default=300,
                  help='Dots-per-inch (DPI) for the output. '
                       'Default is: "%(default)s"')  
    venn_parser.add_argument('--fill', choices=('number','percentage'),default='number',
                  help='Report number or  percentage of overlaps (Only if --type=list)'
                       'Default is "%(default)s"')
    venn_parser.add_argument('--test', action='store_true', help='This will run the program on test data.')


    #upset module argument parser
    upset_parser = subparsers.add_parser('upset', usage='intervene upset [options]', 
        description='Create UpSet diagram after intersection of genomic regions in <BED/GTF/GFF/VCF> or list sets.', 
        help='UpSet diagram of intersection of genomic regions or list sets.')
  
    upset_parser.add_argument('-i', dest='input', nargs="*",
        help='Input genomic regions in <BED/GTF/GFF/VCF> format or list files. '
        'For files in a directory use *.<extension>. e.g. *.bed')

    upset_parser.add_argument('--type', dest='type', choices=('genomic','list'),default='genomic',
                  help='Type of input sets. Genomic regions or lists of genes sets. '
                       'Default is "%(default)s"') 
   
    upset_parser.add_argument('--names', dest='labels', default='A,B,C,D,E,F',
                  help='Comma-separated list of names for input files. '
                       'Default is: --names=A,B,C,D,E,F')
    
    upset_parser.add_argument('--filenames', action='store_true', default=False,
                  help='Use file names as labels instead. '
                       'Default is "%(default)s"')
   
    upset_parser.add_argument('-o', '--output', dest='output', 
                  help='Output folder path where plots will store.'
                       'Default is current working directory.')
    
    upset_parser.add_argument('--order', dest="order",choices=("freq", "degree"), 
                   default='freq',help='The order of intersections of sets. '
                       'e.g. --order degree. Default is "%(default)s"')
    
    upset_parser.add_argument('--ninter', type=int, default=40, 
                  help='Number of top intersections to plot. '
                       'By default all intersections will be plotted.')

    upset_parser.add_argument('--showzero', action='store_true', default=False,
                    help='Show empty overlap combinations. '
                       'Default is "%(default)s"')

    upset_parser.add_argument('--showsize', action='store_true', default=False,
                    help='Show intersection sizes above bars. '
                       'Default is "%(default)s"')
   
    upset_parser.add_argument('--mbcolor', type=str, default='gray23', 
                  help='Color of the main bar plot.'
                       'Default is: "%(default)s"')
    upset_parser.add_argument('--sbcolor', type=str, default='#56B4E9', 
                  help='Color of set size bar plot.'
                       'Default is: "%(default)s"')

    upset_parser.add_argument('--mblabel', type=str, default='No of Intersections', 
                  help='The y-axis label of the intersection size bars.'
                       'Default is: "%(default)s"')
    upset_parser.add_argument('--sxlabel', type=str, default='Set size', 
                  help='The x-axis label of the set size bars.'
                       'Default is: "%(default)s"')
           
    upset_parser.add_argument('--figtype', dest="figtype",choices=('pdf','svg','ps','tiff','png'), 
                   default='pdf',help='Figure type for the plot. '
                       'e.g. --figtype svg. Default is "%(default)s"')    
    upset_parser.add_argument('--figsize', type=tuple, default=(10,6),
                   help='Figure size for the output plot (width,height). '
                       'Default is "%(default)s"')    
    upset_parser.add_argument('--dpi', type=int, dest='dpi', default=300,
                  help='Dots-per-inch (DPI) for the output. '
                       'Default is: "%(default)s"')

    upset_parser.add_argument('--run', action='store_false', default=True,
                    help='Run Rscript if R and UpSetR package is installed. '
                       'Default is "%(default)s"')
    upset_parser.add_argument('--test', action='store_true', help='This will run the program on test data.')


    #pairwise module argument parser
    pairwise_parser = subparsers.add_parser('pairwise', usage='intervene pairwise [options]', 
        description='Pairwise intersection and heatmap of N genomic region sets in <BED/GTF/GFF/VCF> format.',
        help='Pairwise intersection and heatmap of N genomic region sets in <BED/GTF/GFF/VCF> format.')
    
    pairwise_parser.add_argument('-i', dest='input', nargs="*",
        help='Input genomic regions in <BED/GTF/GFF/VCF> format. '
        'For files in a directory use *.<extension>. e.g. *.bed')
    
    pairwise_parser.add_argument('--type', choices=('count','frac','jaccard','fisher','reldist'),
        default='frac', help='Report count/fraction of overlaps or statistical relationships. \n'
                       'frac - Calculates the fraction of overlap. \n'
                       'jaccard - Calculate the Jaccard statistic. '
                       'reldist - Calculate the distribution of relative distances. '
                       'fisher - Calculate Fisher`s statistic. '
                       'Default is "%(default)s"')

    pairwise_parser.add_argument('--htype', dest="htype",choices=("tribar","color", "pie","circle", "square", "ellipse", "number", "shade"), 
                   default='tribar',help='Heatmap plot type. '
                           'Default is "%(default)s"')  
    
    pairwise_parser.add_argument('--names', dest='labels', default='A,B,C,D,E,F',
                  help='Comma-separated list of names for input files. '
                       'Default is: --names=A,B,C,D,E,F')
    
    pairwise_parser.add_argument('--filenames', action='store_true', default=False,
                  help='Use file names as labels instead. '
                       'Default is "%(default)s"')
   
    #'''
    pairwise_parser.add_argument('--enrichment', action='store_true',
                    help='Run randomizations (default 1000, specify otherwise '
                    'with --iterations) on each pairwise comparison and '
                    'compute the enrichment score as '
                    '(actual intersection count + 1) / (median randomized + 1)')

    pairwise_parser.add_argument('--iterations', default=1000, type=int,
                    help='Number of randomizations to perform for enrichement '
                    'scores')
    #'''
    pairwise_parser.add_argument('--genome', help='Required argument if --type=fisher. '
                    'Needs to be a string assembly name like "mm10" or "hg38"')
    pairwise_parser.add_argument('-o', '--output', dest='output', 
                    help='Output folder path where plots will store. '
                       'Default is current working directory.')
    pairwise_parser.add_argument('--barlabel', dest="blabel", default='Set size',
                    help='x-axis label of boxplot if --htype=tribar. '
                       'Default is "%(default)s"')
    pairwise_parser.add_argument('--barcolor', dest="barcolor", default='#53cfff',
                    help='Boxplot color (hex vlaue or name, e.g. blue). '
                       'Default is "%(default)s"') 
    pairwise_parser.add_argument('--fontsize', default=8,
                   help='Label abel fount size. '
                       'Default is "%(default)s"')
    pairwise_parser.add_argument('--space', type=float, default=1.1,
                   help='White space between barplt and heatmap. '
                       'Default is "%(default)s"')
    pairwise_parser.add_argument('--figtype', dest="figtype",choices=('pdf','svg','ps','tiff','png'),  
                   default='pdf',help='Figure type for the plot. '
                       'e.g. --figtype svg. Default is "%(default)s"')    
    pairwise_parser.add_argument('--figsize', nargs=2, type=float, default=(8,6),
                   help='Figure size for the output plot (width,height). '
                       'Default is "%(default)s"')    
   
    pairwise_parser.add_argument('--dpi', type=int, default=300,
                  help='Dots-per-inch (DPI) for the output. '
                       'Default is: "%(default)s"')  
    
    pairwise_parser.add_argument('--test', action='store_true', help='This will run the program on test data.')
    
    parser.add_argument('-v','--version', dest='version', action='version', version='%(prog)s 1.0')

    options = parser.parse_args()

    if not options.command:
        venn_parser.print_help()
        sys.stderr.write('Missing required arguments. ')
        sys.exit(1) 

    if options.command == 'upset':
        plot_type = 'upset'
    else:
        plot_type = 'venn'

    #making the out folder if it doesn't exist
    if options.output:
        output_dir = create_dir(options.output)
    else:
        options.output = create_dir(os.getcwd()+"/InterVene_results")

    #check if user want to user test data to plot and get get test files.
    if options.test:
        print("\nRunning Intervene with test data.\n")
        options.input = get_test_data(options.command)
        options.filenames = True

        #sys.exit(1)

    if options.command =='pairwise':
        print("\nPerforming a pairwise intersection/overlap analysis.\n")
        pairwise.pairwise_intersection(options)
        sys.exit(1)

    output_name =  options.output+'/InterVene_'+options.command+'_'+str(venn_order(options.input))+'way_'+options.type+'.'+options.figtype

    #checke if there are atleast two input bed/list files
    reqd_args = ['input']
    if not options.test:
        for ra in reqd_args:
            if not getattr(options,ra):
                if options.command == 'venn':
                    venn_parser.print_help()
                else:
                    upset_parser.print_help()
                sys.stderr.write('Missing required arg "%s"\n' % ra)
                sys.exit(1)
        if len(options.input) < 2:
          sys.stderr.write('Input should have at least two files.\n')
          sys.exit(1)

    if options.command == 'venn' or options.command == 'upset':
        if not options.type:
            if options.command == 'venn':
                venn_parser.print_help()
            else:
                upset_parser.print_help()
            sys.stderr.write('Missing required arg --type {genomic,list}')
            sys.exit(0)
    
    
    #print(options.filenames)
    #sys.exit(1)
    if venn_order(options.input) == 2:
        
        print('\nGenerating a 2-way "%s" diagram.\n' %options.command)
        
        if options.filenames:
          label_names = get_filenames(options.input)
        elif options.labels:
            label_names = options.labels.split(',')
        else:
            label_names = ['A','B']

        #If the input is a gene list
        if options.type == 'list':
            if options.command == 'upset':
                cmd = 'upset_plot_intervene.R %s %s %s %s %s %s' % ('list',2,output_name, label_names,options.input[0],options.input[1])
                os.system(cmd)
                sys.exit(1)

            else:
                a = open(options.a, 'r').readlines()
                b = open(options.b, 'r').readlines()
                labels = list_venn.get_labels([a, b], fill=[str(options.fill)])
                fig, ax = list_venn.venn2(labels, names=label_names)            
        
        #else input considered as bed file
        else:
            fig, ax = genomic_venn.venn2(input_files=options.input,options=options, names=label_names, plot_type=plot_type)
     
    elif venn_order(options.input) == 3:
        
        print('\nGenerating a 3-way "%s" diagram.\n' %options.command)
        
        if options.filenames:
          label_names = get_filenames(options.input)         
        elif options.labels:
            label_names = options.labels.split(',')
        else:
            label_names = ['A','B','C']
        #If the input is a gene list
        if options.type == 'list':
          a = open(options.input[0], 'r').readlines()
          b = open(options.input[1], 'r').readlines()
          c = open(options.input[2], 'r').readlines()
          labels = list_venn.get_labels([a, b, c], fill=['number'])
          if options.command == 'upset':
            #create an RScript
            upset.create_r_script(labels, label_names, options)

          else:
            fig, ax = list_venn.venn3(labels, names=label_names)          
        #else input considered as bed file
        else:
            fig, ax = genomic_venn.venn3(input_files=options.input,
                options=options, names=label_names, plot_type=plot_type)

    elif venn_order(options.input) == 4:
        
        print('\nGenerating a 4-way "%s" diagram.\n' %options.command)
        
        if options.filenames:
          label_names = get_filenames(options.input)
        elif options.labels:
            label_names = options.labels.split(',')
        else:
            label_names = ['A','B','C','D']
        #If the input is a gene list
        if options.type == 'list':
          a = open(options.input[0], 'r').readlines()
          b = open(options.input[1], 'r').readlines()
          c = open(options.input[2], 'r').readlines()
          d = open(options.input[3], 'r').readlines()
          labels = list_venn.get_labels([a, b, c, d], fill=['number'])
          if options.command == 'upset':
            #create an RScript
            upset.create_r_script(labels, label_names, options)

          else:
            fig, ax = list_venn.venn4(labels, names=label_names)
            
        #else input considered as bed file
        else:
             fig, ax = genomic_venn.venn4(input_files=options.input, 
                options=options, names=label_names, plot_type=plot_type)
            
                   
    elif venn_order(options.input) == 5:
        
        print('\nGenerating a 5-way "%s" diagram.\n' %options.command)
        
        if options.filenames:
          label_names = get_filenames(options.input)   
        elif options.labels:
            label_names = options.labels.split(',') 
        else:
            label_names = ['A','B','C','D','E']
        #If the input is a gene list
        if options.type == 'list':
          a = open(options.input[0], 'r').readlines()
          b = open(options.input[1], 'r').readlines()
          c = open(options.input[2], 'r').readlines()
          d = open(options.input[3], 'r').readlines()
          e = open(options.input[4], 'r').readlines()

          labels = list_venn.get_labels([a, b, c, d, e], fill=['number'])
          if options.command == 'upset':
            #create an RScript
            upset.create_r_script(labels, label_names, options)

          else:
            fig, ax = list_venn.venn5(labels, names=label_names)
        #else input considered as genomic regions file
        else:
            fig, ax = genomic_venn.venn5(input_files=options.input, 
                options=options, names=label_names, plot_type=plot_type)
        
    elif venn_order(options.input) == 6:
        
        print('\nGenerating a 6-way "%s" diagram.\n' %options.command)
        
        if options.filenames:
          label_names = get_filenames(options.input) 
        elif options.labels:
            label_names = options.labels.split(',')
        else:
            label_names = ['A','B','C','D','E','F']
        #If the input is a gene list
        if options.type == 'list':
          a = open(options.input[0], 'r').readlines()
          b = open(options.input[1], 'r').readlines()
          c = open(options.input[2], 'r').readlines()
          d = open(options.input[3], 'r').readlines()
          e = open(options.input[4], 'r').readlines()
          f = open(options.input[5], 'r').readlines()

          labels = list_venn.get_labels([a, b, c, d, e, f], fill=['number'])
          if options.command == 'upset':
            #create an RScript
            upset.create_r_script(labels, label_names, options)
          else:
            fig, ax = list_venn.venn6(labels, names=label_names)
                
        #else input considered as bed file
        else:
            fig, ax = genomic_venn.venn6(input_files=options.input,options=options, names=label_names, plot_type=plot_type)
    
    elif venn_order(options.input) > 6:
      if options.command == 'venn':
        venn_parser.print_help()
      else:
        upset_parser.print_help()
      sys.stderr.write('The number of input files are more than 6.\n')
      sys.exit(1)
    
    else:
        parser.print_help()
        sys.stderr.write('Please make sure your arguments are correct.\n')
        sys.exit(1)

    fig.savefig(output_name, dpi=options.dpi, bbox_inches='tight')
    plt.close()
    print('\nYou are done! Please check your results @ '+options.output+'. \nThank you for using InterVene!\n')

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.stderr.write("I got interrupted. :-( Bye!\n")
        sys.exit(0)
